apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: k8-template
build:
  local:
    push: false                                            # When building locally, do not push the image to a repository
  artifacts:
  - image: k8-template                                         # Image name
    context: .
    jib:                                                   # Use Jib as the container builder
      fromImage: "gcr.io/distroless/java17-debian12"       # Use a "distroless" base image
  tagPolicy:
    dateTime:                                              # The image will be tagged with the build timestamp
      format: "20060102T150405"
      timezone: "UTC"
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/
