# Builds 
name: java-maven-skaffold-build
on:
  workflow_call:
    inputs:
      repositoryFolder: 
        description: "The code repository folder to build. '.' for the root folder, './folder1/mavenRoot/' for a sub-folder"
        default: '.'
        required: false
        type: string
      javaVersion:
        description: 'The Java version to build and deploy. Default is Java 17'
        default: '17'
        required: false
        type: string
jobs:
  build-skaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: "temurin"
          cache: "maven"
      - name: Build image with Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          skaffold-version: 2.1.0
          working-directory: ${{ inputs.repositoryFolder }}
          command: build
          push: false