name: package-01-k8-template
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "01-k8-template/**"
      
jobs:
  package-01-k8-template:
    uses: ./.github/workflows/java-maven-skaffold-build-push-ghcr.yml
    with:
      repositoryFolder: "./01-k8-template/"
    secrets: inherit